pre-commit:
  parallel: true
  jobs:
    - name: Check
      group:
        parallel: true
        jobs:
          - name: editorconfig-checker
            run: ec
          - name: Typos
            run: typos
          - name: Ruff
            group:
              parallel: true
              jobs:
                - name: Check
                  run: ruff check
                - name: Format
                  run: ruff format --check
          - name: ty
            run: ty check
          - name: uv lock
            run: uv lock --check

commit-msg:
  jobs:
    - name: Committed
      run: committed --commit-file ./.git/COMMIT_EDITMSG

check:
  parallel: true
  jobs:
    - name: editorconfig-checker
      run: ec
    - name: Typos
      run: typos
    - name: Ruff
      group:
        parallel: true
        jobs:
          - name: Check
            run: ruff check
          - name: Format
            run: ruff format --check
    - name: ty
      run: ty check
    - name: uv lock
      run: uv lock --check

fix:
  jobs:
    - name: Check
      group:
        parallel: true
        jobs:
          - name: editorconfig-checker
            run: ec
          - name: ty
            run: ty check
          - name: uv lock
            run: uv lock --check
    - name: Fix
      group:
        jobs:
          - name: Typos
            run: typos -w
          - name: Ruff
            group:
              jobs:
                - name: Ruff Check
                  run: ruff check --fix
                - name: Ruff Format
                  run: ruff format
